-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id smallint NOT NULL,
    email character varying NOT NULL,
    password character varying NOT NULL,
    register_date time without time zone NOT NULL,
    activation_code character varying NOT NULL,
    email_confirm boolean NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    id smallint NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    nationality_id character varying NOT NULL,
    birth_year smallint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    id smallint NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id smallint NOT NULL,
    company_name character varying NOT NULL,
    phone_number character varying NOT NULL,
    website character varying NOT NULL,
    admin_confirm boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cvs
(
    id smallint NOT NULL,
    user_id smallint NOT NULL,
    github_link character varying NOT NULL,
    linkedln_link character varying NOT NULL,
    previous_text character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisement
(
    id smallint NOT NULL,
    position_id smallint NOT NULL,
    city_id smallint NOT NULL,
    job_definition character varying NOT NULL,
    min_salary smallint NOT NULL,
    max_salary smallint NOT NULL,
    open_positions_number smallint NOT NULL,
    created_date date NOT NULL,
    expiration_date date NOT NULL,
    employer_id smallint NOT NULL,
    is_active boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id smallint NOT NULL,
    position_name character varying NOT NULL,
    position_description character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id smallint NOT NULL,
    city_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.skills
(
    id smallint NOT NULL,
    cv_id smallint NOT NULL,
    skill character varying NOT NULL,
    skill_level smallint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.experiences
(
    id smallint NOT NULL,
    cv_id smallint NOT NULL,
    workplace_name character varying NOT NULL,
    job_tittle character varying NOT NULL,
    start_date date NOT NULL,
    deparure_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.photos
(
    id smallint NOT NULL,
    cv_id smallint NOT NULL,
    tittle character varying NOT NULL,
    image character varying NOT NULL,
    created_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.educations
(
    id smallint NOT NULL,
    cv_id smallint NOT NULL,
    school_name character varying NOT NULL,
    program_name character varying NOT NULL,
    start_date date NOT NULL,
    graduation_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cv_languages
(
    id smallint NOT NULL,
    cv_id smallint NOT NULL,
    language_name character varying NOT NULL,
    language_level smallint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.skills
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.educations
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.cv_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id)
    NOT VALID;

END;